CREATE TABLE agent_memory_candidates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    candidate_uuid VARCHAR(72) NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    principal_uuid VARCHAR(64) NOT NULL,
    agent_uuid VARCHAR(24) NOT NULL,
    resource_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(128) NOT NULL,
    candidate_type VARCHAR(32) NOT NULL,
    source_id VARCHAR(128) NOT NULL,
    evidence_ids_json JSON NOT NULL,
    summary VARCHAR(4096) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    candidate_sha256 CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    observed_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_memory_candidate_uuid (candidate_uuid),
    KEY idx_agent_memory_candidate_scope (tenant_id, principal_uuid, agent_uuid, resource_type, resource_id, created_at),
    CONSTRAINT chk_agent_memory_candidate_type CHECK (candidate_type IN ('message', 'reflection')),
    CONSTRAINT chk_agent_memory_candidate_status CHECK (status IN ('pending', 'accepted', 'rejected')),
    CONSTRAINT chk_agent_memory_candidate_hash CHECK (candidate_sha256 REGEXP '^[a-f0-9]{64}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
