CREATE TABLE IF NOT EXISTS agent_definition_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    definition_uuid VARCHAR(64) NOT NULL,
    version BIGINT UNSIGNED NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    owner_uuid VARCHAR(20) NOT NULL,
    agent_uuid VARCHAR(20) NOT NULL,
    status VARCHAR(32) NOT NULL,
    permissions_json JSON NOT NULL,
    scopes_json JSON NOT NULL,
    valid_from DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_definition_version (definition_uuid, version),
    UNIQUE KEY idx_agent_definition_tenant_agent_version (tenant_id, agent_uuid, version),
    KEY idx_agent_definition_owner (owner_uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    task_uuid VARCHAR(64) NOT NULL,
    definition_uuid VARCHAR(64) NOT NULL,
    definition_version BIGINT UNSIGNED NOT NULL,
    tenant_id VARCHAR(64) NOT NULL,
    principal_uuid VARCHAR(20) NOT NULL,
    agent_uuid VARCHAR(20) NOT NULL,
    status VARCHAR(32) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    trigger_ref VARCHAR(128) NOT NULL,
    goal TEXT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_task_uuid (task_uuid),
    KEY idx_agent_task_definition (definition_uuid, definition_version),
    KEY idx_agent_task_principal_status (tenant_id, principal_uuid, status),
    KEY idx_agent_task_trigger (trigger_type, trigger_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_approvals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    approval_uuid VARCHAR(64) NOT NULL,
    task_uuid VARCHAR(64) NOT NULL,
    capability_id VARCHAR(128) NOT NULL,
    resource_scope_json JSON NOT NULL,
    scope_sha256 CHAR(64) NOT NULL,
    arguments_sha256 CHAR(64) NOT NULL,
    nonce_sha256 CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    approved_by_uuid VARCHAR(20) NOT NULL DEFAULT '',
    expires_at DATETIME(3) NOT NULL,
    consumed_at DATETIME(3) NULL,
    revoked_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_approval_uuid (approval_uuid),
    UNIQUE KEY idx_agent_approval_nonce (nonce_sha256),
    KEY idx_agent_approval_task_capability (task_uuid, capability_id, status),
    KEY idx_agent_approval_expiry (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
