CREATE TABLE IF NOT EXISTS agent_artifacts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    artifact_uuid CHAR(64) NOT NULL,
    schema_version VARCHAR(64) NOT NULL,
    task_uuid VARCHAR(64) NOT NULL,
    run_uuid VARCHAR(64) NOT NULL,
    artifact_type VARCHAR(64) NOT NULL,
    version INT UNSIGNED NOT NULL,
    title VARCHAR(200) NOT NULL,
    media_type VARCHAR(128) NOT NULL,
    object_bucket VARCHAR(128) NOT NULL,
    object_key VARCHAR(512) NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    metadata_json JSON NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_artifacts_uuid (artifact_uuid),
    UNIQUE KEY idx_agent_artifacts_task_type_version (task_uuid, artifact_type, version),
    UNIQUE KEY idx_agent_artifacts_object (object_bucket, object_key),
    KEY idx_agent_artifacts_task_created (task_uuid, created_at, artifact_uuid),
    CONSTRAINT fk_agent_artifacts_task FOREIGN KEY (task_uuid) REFERENCES agent_tasks(task_uuid),
    CONSTRAINT fk_agent_artifacts_run FOREIGN KEY (run_uuid) REFERENCES agent_runs(run_uuid),
    CONSTRAINT chk_agent_artifacts_schema CHECK (schema_version = 'dipole.agent.artifact.v1'),
    CONSTRAINT chk_agent_artifacts_version CHECK (version > 0),
    CONSTRAINT chk_agent_artifacts_size CHECK (size_bytes > 0 AND size_bytes <= 1048576)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
