CREATE TABLE IF NOT EXISTS agent_model_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_uuid VARCHAR(64) NOT NULL,
    task_uuid VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    max_calls SMALLINT UNSIGNED NOT NULL,
    total_timeout_ms INT UNSIGNED NOT NULL,
    max_output_tokens_per_call INT UNSIGNED NOT NULL,
    calls_reserved SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    started_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    last_error TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_model_runs_uuid (run_uuid),
    UNIQUE KEY idx_agent_model_runs_task (task_uuid),
    KEY idx_agent_model_runs_status (status, updated_at),
    CONSTRAINT chk_agent_model_runs_status CHECK (status IN ('running', 'completed', 'failed')),
    CONSTRAINT chk_agent_model_runs_budget CHECK (max_calls > 0 AND total_timeout_ms > 0 AND max_output_tokens_per_call > 0 AND calls_reserved <= max_calls)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_model_calls (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    call_uuid CHAR(36) NOT NULL,
    run_uuid VARCHAR(64) NOT NULL,
    call_no SMALLINT UNSIGNED NOT NULL,
    route VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    input_tokens INT UNSIGNED NULL,
    output_tokens INT UNSIGNED NULL,
    finish_reason VARCHAR(64) NULL,
    latency_ms INT UNSIGNED NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    last_error TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY idx_agent_model_calls_uuid (call_uuid),
    UNIQUE KEY idx_agent_model_calls_order (run_uuid, call_no),
    KEY idx_agent_model_calls_status (status, updated_at),
    CONSTRAINT fk_agent_model_calls_run FOREIGN KEY (run_uuid) REFERENCES agent_model_runs(run_uuid),
    CONSTRAINT chk_agent_model_calls_status CHECK (status IN ('reserved', 'completed', 'failed', 'abandoned')),
    CONSTRAINT chk_agent_model_calls_number CHECK (call_no > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
