port 26379
bind 0.0.0.0
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor dipole-master redis-1 6379 2
sentinel down-after-milliseconds dipole-master 1500
sentinel failover-timeout dipole-master 10000
sentinel parallel-syncs dipole-master 1
